sudo: false

addons:
  apt:
    packages:
    - build-essential
    - automake
    - texinfo
    - yasm
    - wget
    
before_script:
- wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh -O condainstall.sh
- bash condainstall.sh -b -p $HOME/Anaconda
- source $HOME/Anaconda/bin/activate
- conda config --set always_yes yes
- conda update -q conda
- cd ${TRAVIS_BUILD_DIR}

script:
- python3 tc-builder.py
