sudo: false
language: cpp

addons:
  apt:
    packages:
    - texinfo
    - yasm
    - wget
    
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    
    
before_script:
- wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh -O condainstall.sh
- bash condainstall.sh -b -p $HOME/Anaconda
- source $HOME/Anaconda/bin/activate
- conda config --set always_yes yes
- conda update -q conda
- cd $TRAVIS_BUILD_DIR

script:
- travis_wait 30 python3 tc-builder.py
